
name: Deploy to Server

on:
  push:
    branches:
      - pub
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Pull the latest changes
        run: ssh -o StrictHostKeyChecking=no ubuntu@150.158.9.107 "cd cd /home/ubuntu/xym-ee.github.io && git pull origin pub && systemctl reload nginx"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
