
name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - hugodev  # 触发部署的分支
  workflow_dispatch:  # 允许手动触发
   
jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.131.0'  # 或者指定版本，例如 '0.88.1'

    - name: Build the website
      run: hugo --baseURL="https://xym.work"  # 生成静态文件

    - name: Copy CNAME file
      run: cp CNAME public/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: pub  # 部署到的分支
        publish_dir: ./public  # Hugo 生成的静态文件目录

    - name: SSH to server and pull latest changes
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_NAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu/xym-ee.github.io
          git pull origin pub
          sudo systemctl reload nginx
    
